In [20]:
import numpy as np
#generate random data
data1=np.random.randint(50,size=(93,4))
print(data1)

[[13 19 43 40]
 [14 35 30 47]
 [38 17  9  6]
 [46 27  5 10]
 [ 3 34 46 37]
 [26 17 10 37]
 [26  8 28 13]
 [42 47 43 37]
 [20 35 48 46]
 [ 8 27 15 23]
 [ 5 29 17 13]
 [20 12  1 25]
 [32 24 12  0]
 [12 29 49 19]
 [18  9 47 33]
 [33 34 33 40]
 [43 32 20 34]
 [13 48 42 34]
 [36 34  7 20]
 [10  2 24 13]
 [27 42  1 45]
 [44 38  3 31]
 [49 28  0 46]
 [46  8 43 48]
 [38  5 26 37]
 [39  8 38 33]
 [16 22 35 22]
 [18 16 47 36]
 [42 17 35  4]
 [11 12 20  1]
 [18  4 41  4]
 [30 34 34 45]
 [29 27  0 26]
 [29 27 35 49]
 [38  6 30 37]
 [ 3 12 46 28]
 [ 3  3 31 35]
 [ 4 12 23 19]
 [14  6  8 16]
 [47  0 10 23]
 [18 24  6 32]
 [10 33 15 29]
 [14  5 13 40]
 [39 12  5 10]
 [32 40 12 37]
 [20 10  4  8]
 [15  2 19 22]
 [42 44 13 27]
 [49 14 37  4]
 [ 6  7 26 45]
 [45 37 26 45]
 [ 4 18 21 29]
 [ 9  1 41 25]
 [ 1 25 36 17]
 [ 3 49  6 44]
 [20 35 40  8]
 [22 25 38 41]
 [20  0 46 13]
 [48 20 30 44]
 [ 8 25 27 48]
 [ 2 35 42 49]
 [15 16 45 49]
 [27 34 38 39]
 [37 48 38 35]
 [ 0 20 40  6]
 [ 8 12  7  5]
 [20 39 29